export const ActionTypes = {
    SET_PROCESS_TYPE: "SET_PROCESS_TYPE",
    SET_PROCESS_CONFIG: "SET_PROCESS_CONFIG",
    SET_CONTROLLER_TYPE: "SET_CONTROLLER_TYPE",
    SET_CONTROLLER_CONFIG: "SET_CONTROLLER_CONFIG",
    SET_TUNER_TYPE: "SET_TUNER_TYPE",
    SET_TUNER_CONFIG: "SET_TUNER_CONFIG",
    SET_CONTROL_VALUE_NAME: "SET_CONTROL_VALUE_NAME",
}

export const PID  = "pid"
  