version: "3.3"
services:
  backend:
    build: .
    command: python main.py
    ports:
      - "8080:8080"
    volumes:
      - .:/code
  frontend:
    stdin_open: true
    build:
      context: frontend
      dockerfile: ../Dockerfile-frontend
    command: npm start
    ports:
      - "3000:3000"
    environment:
      - BROWSER=none
      - CI=true
    volumes:
      - ./frontend/src/:/frontend/src
      - ./frontend/public/:/frontend/public
