version: "3.3"
services:
  backend:
    build: .
    command: python main.py
    ports:
      - "8080:8080"
    volumes:
      - .:/code
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    stdin_open: true
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/code
